### ISSUE TITLE
bars in show-volume.py should be explicitly cast to an int or you can get index errors

### ISSUE THREAD

**Issue by calebpalmer** [bchurchill/xmonad-pulsevolume#1]
First of all, thanks very much for this tool!  Very handy.  

In my environment I needed to do this.  Here is the diff:

```
diff --git a/show-volume.py b/show-volume.py
index 5319606..bb63bda 100755
--- a/show-volume.py
+++ b/show-volume.py
@@ -18,7 +18,7 @@ with open(home + "/.mute") as f:

 if isunmuted:
   volume = int(content[0])
-  bars = volume / 9000
+  bars = int(volume / 9000)

   if (volume % 9000 == 0):
     output = allbars[0:bars+1] + emptybars[bars+1:]
```

**Comment by bchurchill** [comment]
Thanks!  If you make a pull request I'll merge it.

<div>-------- Original message --------</div><div>From: Caleb Palmer notifications@github.com </div><div>Date:02/13/2015  11:58  (GMT-08:00) </div><div>To: bchurchill/xmonad-pulsevolume xmonad-pulsevolume@noreply.github.com </div><div>Cc:  </div><div>Subject: [xmonad-pulsevolume] bars in show-volume.py should be explicitly cast
  to an int or you can get index errors (#1) </div><div>
</div>First of all, thanks very much for this tool! Very handy.

In my environment I needed to do this. Here is the diff:

diff --git a/show-volume.py b/show-volume.py
index 5319606..bb63bda 100755
--- a/show-volume.py
+++ b/show-volume.py
@@ -18,7 +18,7 @@ with open(home + "/.mute") as f:

 if isunmuted:
   volume = int(content[0])
-  bars = volume / 9000
-  bars = int(volume / 9000)
  
  if (volume % 9000 == 0):
   output = allbars[0:bars+1] + emptybars[bars+1:]
